### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by therealmikz** [junichi11/netbeans-php-cs-fixer-plugin#12]
It would be useful to have keyboard shortcut instead of right-clicking and searching the context menu everytime you want to fix your cs.

**Comment by junichi11** [comment]
I'll fix it. 
Thanks.

**Comment by junichi11** [comment]
Sorry, I had already fixed this ago.
Please have a look at #7 
You can download it from https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases (0.4.0.1)

I'll update the version number, then upload the new nbm to Pluign Portal.
Thanks.

**Comment by junichi11** [comment]
Updated the version number : 
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.4.1
