### ISSUE TITLE
Already implemented

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-php-cs-fixer-plugin#18]
Hey, What are the pros to use your plugin instead of the Coding Standards FIxer in the php code analysis section of netbeans? I think that this is already implemented in netbeans.

Regards

Chris

**Comment by junichi11** [comment]
Hi,
Yes, I know that because I implemented it.
Unfortunately, Netbeans standard support cannot run the `fix` command at the moment. Just inspect.
So, I'm providing this plugin.

Thanks.

**Comment by Chris2011** [comment]
Ok I understand, I thought that by my self, but why don't you work on your implementation first implementation and fi the problem inside those netbeans standard support?

**Comment by junichi11** [comment]
Well... At first, I created this plugin. Then I created and sent patches for PHP CS Fixer support. At that time, NetBeans team preferred an implementation for code analysis to my plugin's one.

**Comment by Chris2011** [comment]
Hm ok, I don't like the thing, that there is the same functionality twice, as inside of netbeans and when I use the plugin, as the plugin. It should be better to remove it from netbeans I think.

**Comment by junichi11** [comment]
I think... a plugin can be created/published freely by anyone (if it is not the same one completely or not cloned). But an official support should be used proper apis and should be unified similar features. Of course, it would be great if they are unified to one.

Probably, It should be implemented like the inspect and transform feature. But I'm not sure whether I can implement it at the moment, sorry.

**Comment by Chris2011** [comment]
Yeah to implement to inspect and transform would be the best I think or to have a new menu Analyze like in intelliJ were you can have a lot more things. I only gave a hint to remove the built in feature if there is no one who will develop it further, because of this plugin.

**Comment by junichi11** [comment]
I think that there are no problems because it can inspect files actually although it cannot run fix command. 

Thanks.
