### ISSUE TITLE
Error message 'CLI has encountered a problem and needs to close' when running.

### ISSUE THREAD

**Issue by maclearyj** [junichi11/netbeans-php-cs-fixer-plugin#19]
I am using netbeans 8.0.2 running php version 5.3.8 under windows XP (sorry I know its old stuff)!. Whenever I click on the Fix, or Fix --dry-run I immediately get the error messsage:
CLI has encountered a problem and needs to close.  We are sorry for the inconvenience.

**Comment by junichi11** [comment]
Could you try it via your command prompt? If the same error occurs, it's not this plugin's problem. Thanks.

**Comment by maclearyj** [comment]
OK same thing happens from command prompt - sorry to have raised a false issue. 

Regards 
John MacLeary 
Blue Chip Technology Limited. Chowley Oak Lane, Tattenhall, Chester, Cheshire CH3 9EX 
Tel: 01829 772000 Registered in England 3110403 Vat No: GB 618 374134

**Comment by junichi11** [comment]
> sorry to have raised a false issue.

No problem :)

Thanks for your confirmation.
