### ISSUE TITLE
Problem for "run on save"

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-php-cs-fixer-plugin#2]
I can implement "run on save".
But there is a problem. Editor is not reloaded after plugin run fix command on save.
I confirmed that fix command was run once I close the file and reopen it.
So, I'll not provide this feature yet.

**Comment by rjgamer** [comment]
+1 needed

**Comment by Dublerq** [comment]
+1

**Comment by Jon007** [comment]
+1

**Comment by junichi11** [comment]
I tried to fix this problem. Now, the command is run after 1 second. The command may not be run sometimes still. If there is a problem, please submit it as a new issue.

https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.8.0

Thanks.
