### ISSUE TITLE
PHP CS Fixer contextual menu does not appear

### ISSUE THREAD

**Issue by fanphp** [junichi11/netbeans-php-cs-fixer-plugin#20]
Hi,
I'm using NB 8.1, I have problem with this plugin:

Usage

1) Right-click
Project
Directory
File
Editor
2) PHP CS Fixer
fix
fix --dry-run
self-update

the contextual menu does not have the "PHP CS Fixer" option; I see project configuration, but if I right click on project, or directory, or file or in the editor, I don't find the menu item; finally, I don't know how to run it.

Do you know about other plugin conflict? 

Thanks in advance!

**Comment by junichi11** [comment]
There is no action in the project context menu is a bug. But other than that are not one.

Did you set a `php-cs-fixer` path in the Tools > Options > PHP >  Frameworks & Tools > PHP CS FIXER ?

Thanks.

**Comment by junichi11** [comment]
Fixed the project context menu problem.

**Comment by fanphp** [comment]
are you going to update the plugin from Plugin Portal?

**Comment by junichi11** [comment]
> are you going to update the plugin from Plugin Portal?

Yes, later. It would be good if you can test it before that. 
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.5.2

> I don't see context menu neither on directory,nor files or editor

As I wrote the above, did you set it in the Options?
Can you provide screenshots ?

**Comment by fanphp** [comment]
I'd try but when I select the downloaded plugin, it does not appear in the download window! I cannot install it ( see screenshot )

thanks


![dialog_1](https://cloud.githubusercontent.com/assets/16243659/12518135/eea2a2b0-c136-11e5-81f2-78e97ac41da9.jpg)
![dialog_2](https://cloud.githubusercontent.com/assets/16243659/12518136/ef93a12e-c136-11e5-939c-4f22283412ba.jpg)

**Comment by junichi11** [comment]
Did you select it, then click the OK button? If the same version is already installed, it is not shown in the list. (Please check whether it is installed in the installed tab).

My question(Did you set a php-cs-fixer path in the Tools > Options > PHP > Frameworks & Tools > PHP CS FIXER ?) is not that.
![nb-phpcsfixer-issue20-2](https://cloud.githubusercontent.com/assets/738383/12519625/36de40f6-c183-11e5-8cfc-24054978948d.png)

**Comment by fanphp** [comment]
mmmmm,
which kind of Netbeans version are you working with? Mine is 8.1 and there are differences from your screenshot; for example, my PHP CS Fixer configuration is on a different tab called "Code Analisys"
( see screenshot )

![php_code_analisys](https://cloud.githubusercontent.com/assets/16243659/12531625/bc59611c-c1ff-11e5-9602-6accccfb843b.jpg)

In my  "Frameworks & Tools" tab, I don't see "PHP CS Fixer" item!

**Comment by junichi11** [comment]
It's not an answer to my questions... 
Is there **PHP CS Fixer** in the "Frameworks & Tools"? If not, you have not installed this plugin yet.

> Did you select it, then click the OK button? If the same version is already installed, it is not shown in the list. (Please check whether it is installed in the installed tab).

Did you check this? I'm not sure how do you install it. Can you write your exact steps?

> which kind of Netbeans version are you working with?
NB81

> my PHP CS Fixer configuration is on a different tab called "Code Analisys"
It's a standard distribution support. i.e. it's not options for this plugin. **Coding Standard Fixer** is official support. **PHP CS Fixer** is community support.

**Comment by junichi11** [comment]
NOTE: Standard distribution support doesn't have context menu actions. Then, it cannot run the `fix` command. 
Thanks.

**Comment by fanphp** [comment]
Hi, 
I have reinstalled the plugin from Plugin Manager directly, and now it works fine! I can see PHP CS Fixer in in Frameworks & Tools, and not it works well. The version I'm using now is 0.5.1

Thanks!

**Comment by junichi11** [comment]
> I have reinstalled the plugin from Plugin Manager directly, and now it works fine! I can see PHP CS Fixer in in Frameworks & Tools, 

:+1: 

> and not it works well. The version I'm using now is 0.5.1

??? not?

**Comment by fanphp** [comment]
eheheh, I'm sorry, "NOW" it works well !!! 

Thanks for support!!

**Comment by junichi11** [comment]
No problem :+1:
