### ISSUE TITLE
Context menu options not available

### ISSUE THREAD

**Issue by twifty** [junichi11/netbeans-php-cs-fixer-plugin#21]
On the latest version of the netbeans dev build, and using this plugin (not the one built into netbeans) several items are missing. The docs say to right click on a file or folder, and there will be 'fix' option listed. Well, there isn't.

Very easy to reproduce, just install the plugin, configure the source and default config "PHP >> Code Analysis >> Coding Standards Fixer", then right click on a file.

**Comment by junichi11** [comment]
> "PHP >> Code Analysis >> Coding Standards Fixer", then right click on a file.

This is wrong. I'll fix the README file because I noticed that it is old.

Please check PHP > Frameworks & Tools > PHP CS Fixer.

BTW, now I looked at your issue on PHP CS Fixer repo. I understood now, the error message is output to stderr. So we can fix it in NetBeans.

Thanks!

**Comment by junichi11** [comment]
Fixed README.md on the nb81 branch.
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/tree/nb81#global

Thanks.

**Comment by twifty** [comment]
I've discovered why I'm not seeing 'CS Fixer' in the context menu. It doesn't appear for any projects/folders/files which are under 'git' control. Since my whole project is under 'git' it lead me to believe it wasn't working.

So, to reproduce this bug. Open/create a project. Add a folder with a few files, then add them to git. Those controlled files will not have the 'CS Fixer' in the context menu.

BTW, somehow stderr was being output to the console. I have since reinstalled everything with fresh configs and I no longer see the message.

**Comment by junichi11** [comment]
I cannot reproduce it.

![nb-cs-fixer-issue21-1](https://cloud.githubusercontent.com/assets/738383/13191947/056b5b42-d7ab-11e5-958b-2f9d599796d5.png)


Did you check your options as I wrote the above?(did you set the php-cs-fixer path?)

![nb-cs-fixer-issue21-2](https://cloud.githubusercontent.com/assets/738383/13191951/0c46ad7c-d7ab-11e5-8476-d494b44eeb5e.png)

If you don't set options, context menu is not shown.

**Comment by twifty** [comment]
I've figured it out, and it's not primarily related to git. I figured out that any project with a 'composer.json' will not show the context menu. Right clicking on the folder and selecting "open project of folder" will open the project, then the context menu becomes available, and will remain available even after closing that project. Try it with any composer package.

I thought 'git' because my projects are also composer controlled.

**Comment by junichi11** [comment]
> I figured out that any project with a 'composer.json' will not show the context menu.

I cannot reproduce it.
![nb-cs-fixer-issue21-3](https://cloud.githubusercontent.com/assets/738383/13194000/961b65a4-d7c6-11e5-9d97-5bc7b3eea500.png)

> Right clicking on the folder and selecting "open project of folder" will open the project, then the context menu becomes available, and will remain available even after closing that project. 

I'm not sure what this means... Can you attach screenshots?

**Comment by twifty** [comment]
I meant to say, a subproject with a composer.json. In your example above, only your main project has the file, which is open. If you have a subfolder/subproject with a composer, that's where the issue begins. Take for example a simple Symfony project. There will be many 3rd party sources in the 'vendor' directory, each of which has it's own composer.json. These subprojects will not display the menu unless the project is first opened.

In my case, I am working on subprojects in the 'src' directory, which are backed up to github and have a composer.json.

**Comment by junichi11** [comment]
Just provide a simple reproducible project with exact steps to reproduce it. (e.g. via GitHub public repo.)
It is hard to understand your context if you write only its explanation.
Why don't you provide screenshots, a sample project , e.t.c. ? It is easy to reproduce it.

**Comment by twifty** [comment]
OK, clone and open [SimpleProject](https://github.com/twifty/NB-CS-Fixer.git)

The 'SimpleSource' directory and anything under it has the context menu. The 'SubProject' doesn't. This is because 'SubProject' contains a composer.json file. Right clicking on 'SubProject' and selecting "open project of folder" will open a new project. The context menu will now be available in the primary project, even after closing the new project. This can be reset by deleting the 'nbproject' directory.

**Comment by junichi11** [comment]
Thanks! It's reproducible. 
I'll fix it.

**Comment by junichi11** [comment]
I've fixed it. 
Please try using the new version : 
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.5.3

Thanks!

**Comment by twifty** [comment]
It's working like a dream now. Thanks for fixing it so quick.
