### ISSUE TITLE
PHP-CS-Fixer 2.0 is out

### ISSUE THREAD

**Issue by ManuDoni** [junichi11/netbeans-php-cs-fixer-plugin#22]
This plugin is not compatible with 2.0 version.
the main reasons are that `--fixers`  and `--level` params has been unified to `--rules` and the `--config`
param now is a path to .php_cs config file (like `--config-file` done before).
Here is a migration guide: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/v2.0.0/UPGRADE.md
I'll be very grateful if you could make this plugin (or maybe a new one) compatible with this new version

**Comment by junichi11** [comment]
Thanks for reporting.
I'll look at it later. Sorry, I cannot promise to do it soon.

**Comment by ManuDoni** [comment]
> Sorry, I cannot promise to do it soon

Sure, thanks anyway!

I love this plugin, thanks a lot for your work.

**Comment by junichi11** [comment]
> I love this plugin, thanks a lot for your work.

You are welcome :) I'm so glad to hear that. Thanks!

**Comment by junichi11** [comment]
Done!

Please try to use the following:
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.6.0

**NOTE:**
First, if PHP-CS-Fixer 2.x is used, the `Version` option must be selected in the options panel.
I've just added the `rules` option. Other than that, we can use the `custom` option.

Thanks.
