### ISSUE TITLE
No options

### ISSUE THREAD

**Issue by SoftCreatR** [junichi11/netbeans-php-cs-fixer-plugin#23]
I've just installed v.0.6.0 and set options, but there's no context menu item to run the fixer.

**Comment by junichi11** [comment]
I cannot reproduce it.
Did you set the path of php-cs-fixer?

My environment:
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM 25.111-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_111-b14
System: Linux version 4.4.0-51-generic running on amd64; UTF-8;

![nb-phpcsfixer-issue23](https://cloud.githubusercontent.com/assets/738383/20920680/4745019e-bbe4-11e6-8fc6-d14d61500c4a.png)

**Comment by SoftCreatR** [comment]
![bildschirmfoto 2016-12-06 um 11 07 28](https://cloud.githubusercontent.com/assets/81188/20921404/3729e1ac-bba4-11e6-98da-a8d82eef7c6c.png)

```
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Java: 1.8.0_101; Java HotSpot(TM) 64-Bit Server VM 25.101-b13
Runtime: Java(TM) SE Runtime Environment 1.8.0_101-b13
System: Mac OS X version 10.12.1 running on x86_64; UTF-8; de_DE (nb)
```

**Comment by junichi11** [comment]
No, It's "Code Analysis"(Official support). This plugin's option is "Frameworks & Tools". See https://github.com/junichi11/netbeans-php-cs-fixer-plugin#global

Thanks.

**Comment by SoftCreatR** [comment]
Oh... :D 

Ty.
