### ISSUE TITLE
Source Inspect results not as expected - Netbeans 8.2/OSX

### ISSUE THREAD

**Issue by Jon007** [junichi11/netbeans-php-cs-fixer-plugin#27]
#### Overview description
Results output not as expected in Netbeans 8.2 on OSX.

#### Steps to reproduce
1. configure php-cs-fixer 
![Coding Standards Fixer](https://jonmoblog.files.wordpress.com/2017/05/netbeans-phpfixer-options.jpg)
2. in Netbeans do File, New project, PHP Application
3. in the new index.php, make a poorly formatted edit, so now the total project php is `like:`
```
		<?php
		// put your code here
								echo('this is my code');
		?>

```
4. Run Source, Inspect

#### Actual results
results show a long text output of problems incorrectly marked as line 1
![php-cs-fixer result](https://jonmoblog.files.wordpress.com/2017/05/netbeans-php-cs-fixer.jpg)

#### Expected results
I expected inspector to show problem line numbers and problems as per Code Sniffer:
![CodeSniffer example](https://jonmoblog.files.wordpress.com/2017/05/netbeans_codesniffer.jpg)

#### Version number of the plugin
Version: 0.5.3 Source: 1456105861_org-netbeans-modules-php-phpcsfixer-0.5.3.nbm

#### Version information of NetBeans
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 1
Java: 1.8.0_05; Java HotSpot(TM) 64-Bit Server VM 25.5-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_05-b13
System: Mac OS X version 10.12.4 running on x86_64; UTF-8; en_GB (nb)

**Comment by junichi11** [comment]
Unfortunately, this is not this plugin's problem. Code Analysis features are official support. AFAR, PHP-CS-Fixer has the cause of the line number. NetBeans just uses an XML output for PHPCSFixer(with --dry-run option). But probably, it doesn't have values for lines. So please try to check it. If it is true, you should request to add it to XML output for PHPCSFixer.

**Comment by Jon007** [comment]
ok, I see the plugin is supposed to be configured under "Frameworks and Tools" rather than "Code Analysis", so after doing that I'm still not quite sure:

- so the Source, Inspect is not controlled by this plugin?
- so actually this plugin does not integrate with the Netbeans Editor at all?   in terms of hints etc etc

and why is it necessary to duplicate the setting for php cs fixer in the Code Analysis and Frameworks and Tools tabs?

**Comment by Jon007** [comment]
ok I get it
