### ISSUE TITLE
Feature request - disable output window

### ISSUE THREAD

**Issue by twifty** [junichi11/netbeans-php-cs-fixer-plugin#28]
IDE real estate is becoming more and more valuable. When doing simple edits to a class, I often find myself running cs-fixer as a formatting tool. Each time it is run, it also writes to and opens the output pane in the netbeans IDE. This can be quite annoying sine the output only tells me which files have been changed, which is kinda redundant since I only selected a single file.

To add to the annoyance, the output pane always opens at it's last open size. While debugging the is often quite large, taking up about half of the screen.

As a feature request, can you add an option to completely disable output, or better still, the option to disable when only a single file is passed through. Something along the lines of two check boxes:

[ ] disable single file output
[ ] disable multi file output

I would submit a PR myself, but my java coding is quite honestly terrible.

**Comment by junichi11** [comment]
I'll just add the "No output" option.

Thanks.

**Comment by twifty** [comment]
Either or would be great. Thanks.

**Comment by junichi11** [comment]
I've added a new option for an output window ("Show an output window": Not "No output", sorry).

https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.7.0

**NOTE:** If dry-run command is run, an output window is shown even if the option is unchecked.

Thanks.

**Comment by twifty** [comment]
Works great. Thanks for the quick update
