### ISSUE TITLE
Publish plugin for NetBeans 8.2

### ISSUE THREAD

**Issue by ddegasperi** [junichi11/netbeans-php-cs-fixer-plugin#29]
Hi,

can you publish the builds of the versions > 0.5.3 in the plugin catalogue of NetBeans?

Best regards,
Daniel

**Comment by junichi11** [comment]
Thanks for the heads up. I forgot to upload it to the PP. 
Now, It's available:
- http://plugins.netbeans.org/plugin/49042/php-cs-fixer
- https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases
