### ISSUE TITLE
Put the cache file in the metadata directory

### ISSUE THREAD

**Issue by mlambley** [junichi11/netbeans-php-cs-fixer-plugin#31]
When I create a project in Netbeans I tick the box "Put NetBeans metadata into a separate directory" to reduce clutter in my project.

![image](https://user-images.githubusercontent.com/17264636/40948296-009e86b4-68ab-11e8-9239-2a463faeed4e.png)

However, the PHP CS Fixer plugin creates its `.php_cs.cache` in my project directory, which is extra clutter. Is there a way to use the project metadata directory instead? Or perhaps the NetBeans cache directory, which is found in Help -> About?

Edit: I have worked around this issue by adding `--using-cache=false` but it would be nice to be able to use the cache.

Thanks.

`NetBeans:` 8.2 (Build 201705191307)
`PHP CS Fixer Plugin:` 0.8.1

**Comment by junichi11** [comment]
Please use the `--cache-file` option.
![screenshots-issue31](https://user-images.githubusercontent.com/738383/40949170-bacbe058-68a7-11e8-90f7-aca657abdcb5.png)

**Comment by mlambley** [comment]
If I use that option with multiple projects, will it override my cache file each time?

**Comment by mlambley** [comment]
![image](https://user-images.githubusercontent.com/17264636/40950273-739c6668-68b5-11e8-9b6b-c366d0857b11.png)

That's the relative path, not the full path. So if I have a file with the same relative path in a different project would it not conflict?

**Comment by junichi11** [comment]
This isn't the plugin's problem, I think. Unfortunately, I'm not an expert of PHP CS Fixer. So please ask PHP CS Fixer people about that.

Thanks.

**Comment by mlambley** [comment]
As I suggested above, does the plugin have access to the Netbeans Project Metadata Directory? Can the plugin tell CS Fixer to use the metadata directory for its cache?

**Comment by junichi11** [comment]
> As I suggested above, does the plugin have access to the Netbeans Project Metadata Directory?

Basically, No. Probably, need hacks. I wouldn't do it.

> Can the plugin tell CS Fixer to use the metadata directory for its cache?

Only adding the `--cache-file` option. i.e. The same as adding it to project properties manually. This plugin just run PHP CS Fixer commands.

As I wrote above, You can use `--cache-file` option to change a `.php_cs.cache` file path. Maybe, `/path/to/YourSpecifiedDirectory/YourProjectName/nbproject/.php_cs.cache` Just give it a try. I'm not sure but maybe it should be OK because you can set the path per project. If you find some problems, please ask PHP CS Fixer guys.

**Comment by mlambley** [comment]
Per-project settings should be good enough. Thank you.
