### ISSUE TITLE
How to pass multiple arguments?

### ISSUE THREAD

**Issue by BLaDZer** [junichi11/netbeans-php-cs-fixer-plugin#35]
#### Issue type

- [x] bug
- [ ] enhancement

#### Overview description
Hello @junichi11. Currently I'm encounter a problem when trying to pass two arguments:

1. --config
2. --path-mode

and got an error "Cannot read config file ".php_cs.dist --path-mode=intersection"". This is because plugin execute script in this way:

```
"/usr/bin/php" "/home/blad/php-cs-fixer.phar" "fix" "test.php" "--config=.php_cs.dist --path-mode=intersection" "--ansi" "--no-interaction"
```

#### Steps to reproduce

1. In plugin config set "custom" input to "--config=<path_to_config> --path-mode=intersection" with/without quotes
2. Execute php-cs-fixer with plugin

#### Actual results
"Cannot read config file ".php_cs.dist --path-mode=intersection""

#### Expected results
php-cs-fixer.phar recieve all passed arguments

#### Your environment (NetBeans and plugin version, e.t.c.)
Linux
NetBeans 11.2
PHP CS Fixer - plugin 0.10.0
PHP CS Fixer 2.16.1

**Comment by BLaDZer** [comment]
I really hope for your help

**Comment by junichi11** [comment]
@BLaDZer I have a question. It works fine via your terminal, doesn't it?
I'll fix it.

**Comment by BLaDZer** [comment]
Yes it works fine when in terminal I manually separate all arguments in own double quotes, like this:
```
"php" "php-cs-fixer.phar" "fix" "test.php" "arg1" "arg2" "argN"
```
Or if I provide only one argument "config" or "path-mode"

> I'll fix it.

Thank you very much

**Comment by junichi11** [comment]
@BLaDZer 
Could you test dev version (0.10.0.1-dev)? : https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.10.0

**Comment by BLaDZer** [comment]
@junichi11 sorry but I do not see any changes - still same error. Plugin was reinstalled with your file

**Comment by junichi11** [comment]
@BLaDZer Oops, I'm sorry. It seems that I've uploaded to the old file... I've upload the new nbm again. Please try using it. Thanks.

**Comment by BLaDZer** [comment]
Yes it's working now. Please don't remember to fix same behavior in project config page. It's not working as expecting when configuring from there

**Comment by junichi11** [comment]
Done: https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.10.1

**Comment by BLaDZer** [comment]
@junichi11 can I ask you to update version on NetBeans plugin portal, please. Thanks
