### ISSUE TITLE
Doesn't work on Windows with Apache NB 12.3

### ISSUE THREAD

**Issue by VinceT** [junichi11/netbeans-php-cs-fixer-plugin#37]
#### Issue type

- [x] bug
- [ ] enhancement

#### Overview description
In tab "Frameworks & tools", the field "PHP CS Fixer" does not accept php-cs-fixer.bat, but only php-cs-fixer. Adding manually the .bat extension clears the field after validating.
If I try without the extension, due to the fact that it's a bash shell, I get the following error :

java.io.IOException: CreateProcess error=193, %1 n’est pas une application Win32 valide

#### Steps to reproduce

1. 
2. 
3. 

#### Your environment (NetBeans and plugin version, e.t.c.)
Apache NetBeans 12.3 x64
PHP : 8.0.6 x64
Plugin : 0.11.0
"friendsofphp/php-cs-fixer": "^3.0" (installed in the project using Composercat)

**Comment by junichi11** [comment]
@VinceT 
Could you please try using this (0.11.0.1-dev)?
https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.11.0

**Comment by junichi11** [comment]
Done. https://github.com/junichi11/netbeans-php-cs-fixer-plugin/releases/tag/v0.11.1
